#!/bin/bash

echo Configuring AAlarm...

PATH_INSTALL="/usr/share/aalarm"
PATH_INSTALL_BIN="/usr/bin"
PATH_INSTALL_SH="/usr/share/aalarm/sh"
PATH_INSTALL_CONF="/etc/aalarm"

#create pid dir
mkdir -p $PATH_INSTALL/pid
#create motion captures dir
mkdir -p $PATH_INSTALL/webDj/static/motion

#mod config.sh
cp $PATH_INSTALL_CONF/config.sh.dist $PATH_INSTALL_CONF/config.sh
sed -i "s|PATH_AALARM|$PATH_INSTALL|g" $PATH_INSTALL_CONF/config.sh

#mod aalarm.conf
cp $PATH_INSTALL_CONF/aalarm.conf.dist $PATH_INSTALL_CONF/aalarm.conf
sed -i "s|PATH_AALARM|$PATH_INSTALL|g" $PATH_INSTALL_CONF/aalarm.conf

#mod settings.py
cp $PATH_INSTALL/webDj/djangoAAlarm/settings.py.dist $PATH_INSTALL/webDj/djangoAAlarm/settings.py
sed -i "s|PATH_AALARM|$PATH_INSTALL|g" $PATH_INSTALL/webDj/djangoAAlarm/settings.py

#mod urls.py
cp $PATH_INSTALL/webDj/djangoAAlarm/urls.py.dist $PATH_INSTALL/webDj/djangoAAlarm/urls.py
sed -i "s|PATH_AALARM|$PATH_INSTALL|g" $PATH_INSTALL/webDj/djangoAAlarm/urls.py

#replace path in executable files
sed -i "s|AALARM_PATH_FOLDER_CONFIG|$PATH_INSTALL_CONF|g" $PATH_INSTALL_BIN/startAAlarmServices.sh
sed -i "s|AALARM_PATH_FOLDER_CONFIG|$PATH_INSTALL_CONF|g" $PATH_INSTALL_BIN/stopAAlarmServices.sh
sed -i "s|PATH_AALARM|$PATH_INSTALL|g" $PATH_INSTALL_BIN/startAAlarmServices.sh

sed -i "s|PATH_AALARM|$PATH_INSTALL|g" $PATH_INSTALL_SH/cleanMotion.sh
sed -i "s|AALARM_PATH_FOLDER_CONFIG|$PATH_INSTALL_CONF|g" $PATH_INSTALL_SH/startPlaylist.sh
sed -i "s|AALARM_PATH_FOLDER_CONFIG|$PATH_INSTALL_CONF|g" $PATH_INSTALL_SH/statusPlaylist.sh
sed -i "s|AALARM_PATH_FOLDER_CONFIG|$PATH_INSTALL_CONF|g" $PATH_INSTALL_SH/stopPlaylist.sh
sed -i "s|AALARM_PATH_FOLDER_CONFIG|$PATH_INSTALL_CONF|g" $PATH_INSTALL_SH/zmLast.sh

sed -i "s|AALARM_PATH_FOLDER_CONFIG|$PATH_INSTALL_CONF|g" $PATH_INSTALL/pl/alarmSerialController.pl

#permissions

chmod 755 $PATH_INSTALL_SH/*
chmod 755 $PATH_INSTALL_BIN/startAAlarmServices.sh
chmod 755 $PATH_INSTALL_BIN/stopAAlarmServices.sh
chmod 755 $PATH_INSTALL/pl/alarmSerialController.pl
chmod 755 $PATH_INSTALL/webDj/manage.py

echo Install done
echo Please edit $PATH_INSTALL/webDj/djangoAAlarm/settings.py with your db settings
echo Please edit $PATH_INSTALL_CONF/aalarm.conf with your db and other settings
 